### ISSUE TITLE
Ojuju Project Checklist

### ISSUE THREAD

**Issue by bghryct** [jobosonchisa/ojuju#1]
**MILESTONE 1**
- [x] Concept for design
- [x] Contract Signing 
- [x] GitHub setup complete
- [x] PROTOTYPE HamburgefontsivHAMBURGEFONTSIV!., “space char”
- [x]  Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?
- [x] Checking glyph coverage for milestone?
- [x] Google Fonts Template and font building for your project?  Check the actions tab.

_Path direction correction_
- [x] Are all characters interpolating? select all in font tab and fix path direction shift+command+R

_Not necessary in Repo but good for reviewers_
- [x] proofing with font proofer or similar tools.
- [x] are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [x] Are proofs being sent to reviewers for feedback?

_Spacing_
- [x] spacing is tested with spacing strings
- [x] capitals are spaced to work with lowercase letters

**MILESTONE 2**
- [x] 53+ glyphs both weights
- [x] 80+ glyphs, incl A-Z, a-z 0-9, punctuation both weights
- [x]  Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

_Path direction correction_
- [x] Are all characters interpolating? select all in font tab and fix path direction shift+command+R

_Not necessary in Repo but good for reviewers_
- [x] proofing with font proofer or similar tools.
- [x] are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [x] proofs are made with randomized text, and tested at the range of Weights defined in the project brief
- [x] Are proofs being sent to reviewers for feedback?

**MILESTONE 3**
- [x] 100+ characters incl. A-Z, a-z, 0-9 in font with weight axis
- [x] Diacritics (in sets of western euro, vietnamese, floating, attached)
- [x] Special SSA characters/ Diacritics
- [x] Diacritics are built from combining forms + anchor points
- [x] Diacritics fit into vertical metrics
- [x]  Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

_Path direction correction_
- [x] Are all characters interpolating? select all in font tab and fix path direction shift+command+R
- [x] Are all overlaid diacritics using the same path direction?

_Not necessary in Repo but good for reviewers_
- [x] proofing with font proofer or similar tools.
- [x] are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

**MILESTONE 4**
- [x] Full SSA Google charset ~1100 characters 
- [x]  Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

_Spacing_
- [x] Kerning with Kern On and reviewing kerning (lowercase-lowercase, Capital-lowercase, numerals)

_Path direction correction_
- [x] Are all characters interpolating? select all in font tab and fix path direction shift+command+R

_Not necessary in Repo but good for reviewers_
- [x] proofing with font proofer or similar tools.
- [x] are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

**MILESTONE 5**
- [x] Additional fixing?
- [x] Fontbakery Bug Fixes
- [x]  Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?

**MILESTONE 6**
- [x] All glyphs complete and known bugs fixed
- [x] Review with onboarding team

**MILESTONE 7**

- [x] Social media promotion, additional static and animated assets 
produced, print-on-demand merchandise available

- [x] Pull request to Google fonts made? Add font issue to google fonts filed?
